### ISSUE TITLE
cannot import name 'find_bounding_rect' from 'segm' 

### ISSUE THREAD

**Issue by drevald** [ssppkenny/libsegm#2]
File "/Users/denis/Documents/Projects/libsegm/scripts/cluster.py", line 9, in <module>
    from segm import join_rects, find_bounding_rect, glyph_result
ImportError: cannot import name 'find_bounding_rect' from 'segm' (/Users/denis/Documents/Projects/libsegm/.venv/lib/python3.9/site-packages/segm-0.1-py3.9-macosx-10.15-x86_64.egg/segm/__init__.py)

**Comment by ssppkenny** [comment]
Please check the following:
python
>>> import segm
>>> dir(segm)
>>> ['SegmentationException', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_segm', 'find_baseline', 'find_bounding_rect', 'find_bounding_rects_for_words', 'find_clusters', 'find_glyphs', 'find_grouped_glyphs', 'find_interword_gaps', 'find_neighbors', 'find_ordered_glyphs', 'find_word_limits', 'get_baseline', 'get_bounding_rect', 'get_bounding_rects_for_words', 'get_clusters', 'get_glyphs', 'get_grouped_glyphs', 'get_interword_gaps', 'get_joined_intervals', 'get_joined_rects', 'get_neighbors', 'get_ordered_glyphs', 'get_word_limits', 'glyph_result', 'join_intervals', 'join_rects']

You should see something like this. Check if find_bounding_rect' is in the list.

**Comment by drevald** [comment]
>>> import segm
>>> dir(segm)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_segm', 'find_glyphs', 'get_glyphs', 'get_joined_rects', 'glyph_result', 'join_rects']

**Comment by ssppkenny** [comment]
It looks like you still have an old version.
Please recompile and install 
python setup.py build && python setup.py install
